imports:
    - { resource: 'services/weather/api/open_weather_map_client.yaml' }
    - { resource: 'services/facebook/selenium/facebook_client.yaml' }
    - { resource: 'services/openAi/api/open_ai_client.yaml' }
    - { resource: 'services/huggingFace/api/hugging_face_inference_client.yaml'}

services:
    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    #Contoller for developing
    Sender\Sender\SomeController:
        class: Sender\Sender\SomeController
        autowire: true
        autoconfigure: true
        arguments:
            $cityWeather: '@Sender\Sender\Core\Source\Weather\Infrastructure\Api\CityWeatherInterface'
            $sendMessage: '@Sender\Sender\Core\Distribution\Channel\Facebook\Infrastructure\Selenium\SendMessageInterface'