imports:
    - { resource: 'services/weather/api/open_weather_map_client.yaml' }
    - { resource: 'services/facebook/api/facebook_client.yaml' }

services:
    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    #Contoller for developing
    Sender\Sender\SomeController:
        class: Sender\Sender\SomeController
        autowire: true
        autoconfigure: true
        arguments:
            $cityWeather: '@Sender\Sender\Core\Source\Weather\Infrastructure\Api\CityWeatherInterface'