parameters:
  facebook_page_access_token: '%env(FACEBOOK_PAGE_ACCESS_TOKEN)%'
  facebook_base_url: '%env(FACEBOOK_BASE_URL)%'
  selenium_host: '%env(SELENIUM_HOST)%'
  facebook_email: '%env(FACEBOOK_EMAIL)%'
  facebook_password: '%env(FACEBOOK_PASSWORD)%'
  facebook_group_id: '%env(FACEBOOK_GROUP_ID)%'

services:
  Sender\Sender\Core\Distribution\Channel\Facebook\Infrastructure\Api\Client\FacebookClient:
    class: Sender\Sender\Core\Distribution\Channel\Facebook\Infrastructure\Api\Client\FacebookClient
    arguments:
      $key: '%facebook_page_access_token%'
      $url: '%facebook_base_url%'
      $client: '@GuzzleHttp\Client'

  Sender\Sender\Core\Distribution\Channel\Facebook\Infrastructure\Api\SendMessageInterface:
    alias: Sender\Sender\Core\Distribution\Channel\Facebook\Infrastructure\Api\Client\FacebookClient

  Sender\Sender\Core\Distribution\Channel\Facebook\Application\Service\SendMessageService:
    arguments:
      $host: '%selenium_host%'
      $email: '%facebook_email%'
      $password: '%facebook_password%'